_target_: tasks.gaussian_process.GPTask

name: AL_data

dim_x: 1
dim_y: 1

# Target mask parameters
embedding_type: data
mask_type: ["all"]
n_selected_targets: null  # later for partial mode
predefined_masks: null
predefined_mask_weights: null
mask_index: null  # no need for data mode
attend_to: null  # for split mode, we want to only attend to data or theta

n_context_init: 1
n_query_init: 200

n_target_data: 100
n_target_theta: 0

design_scale: 5
noise_scale: 0.01

lengthscale_lower: 0.1
lengthscale_upper: 2.0



